apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubernetes-operator.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubernetes-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: controller-manager
      {{- include "kubernetes-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
        {{- include "kubernetes-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kubernetes-operator.serviceAccountName" . }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --metrics-bind-address=:{{ .Values.metrics.port }}
            - --health-probe-bind-address=:{{ .Values.health.port }}
            {{- if .Values.leaderElection.enabled }}
            - --leader-elect
            {{- end }}
          ports:
            - containerPort: 9443
              name: webhook-server
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.health.port }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.health.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
