{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kubernetes-operator.fullname" . }}-metrics-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubernetes-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      {{- include "kubernetes-operator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
